# Generated by Django 3.0.6 on 2022-08-26 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='concursos',
            fields=[
                ('fechaIni', models.DateTimeField(blank=True, null=True)),
                ('fechaCreado', models.DateField(blank=True, null=True)),
                ('problema', models.FileField(null=True, upload_to='concursos', verbose_name='concurso')),
                ('activo', models.BooleanField(blank=True, default=False, null=True)),
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Codigonombre', models.CharField(max_length=50, null=True, verbose_name='Còdigo')),
                ('preciodeInsc', models.IntegerField(null=True, verbose_name='Precio')),
                ('participantes', models.IntegerField(null=True, verbose_name='Participantes')),
            ],
        ),
        migrations.CreateModel(
            name='correoValidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('codigo', models.IntegerField()),
                ('validado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, null=True, verbose_name='Título')),
                ('autor', models.CharField(max_length=50, null=True, verbose_name='Autor')),
                ('edicion', models.CharField(max_length=50, null=True, verbose_name='Edición')),
            ],
        ),
        migrations.CreateModel(
            name='paquetes',
            fields=[
                ('paqueteID', models.AutoField(primary_key=True, serialize=False)),
                ('paqueteCod', models.CharField(max_length=50, null=True, verbose_name='Codigo del paquete')),
                ('paqueteCant', models.IntegerField(null=True, verbose_name='Cantidad de problemas que contiene')),
                ('paquetePrecio', models.IntegerField(null=True, verbose_name='Precio')),
                ('paqueteDias', models.IntegerField(null=True, verbose_name='Dias que estará activo')),
                ('paqueteDescr', models.CharField(max_length=50, null=True, verbose_name='Descripción')),
                ('paqueteFecha', models.DateField(auto_now_add=True, null=True)),
                ('paqueteCreador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='perfil',
            fields=[
                ('perfilID', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePerfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QRPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr', models.ImageField(null=True, upload_to='qr')),
                ('Nombre', models.CharField(max_length=50, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto')),
            ],
        ),
        migrations.CreateModel(
            name='solucionadores',
            fields=[
                ('solucionadorNombre', models.CharField(max_length=50)),
                ('solucionadorID', models.AutoField(primary_key=True, serialize=False)),
                ('solucionadorPais', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField(null=True)),
                ('fechaIni', models.DateField(blank=True, null=True)),
                ('fechaPago', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('vencido', models.BooleanField(blank=True, default=False, null=True)),
                ('paqueteMio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.paquetes')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioConcurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.concursos')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tematicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temaNombre', models.CharField(max_length=50, null=True, verbose_name='Nombre del Tema')),
                ('agregadoPor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por:')),
                ('perfilId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.perfil', verbose_name='Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='soluciones',
            fields=[
                ('problemaNumero', models.CharField(max_length=50, null=True, verbose_name='Numero del Problema')),
                ('problemaProblema', models.ImageField(null=True, upload_to='problemas', verbose_name='Figura del problema')),
                ('problemaID', models.AutoField(primary_key=True, serialize=False)),
                ('problemaSolucion', models.FileField(null=True, upload_to='soluciones', verbose_name='Documento de solución')),
                ('problemaVideo', models.FileField(null=True, upload_to='videos', verbose_name='Audio de explicación')),
                ('problemaFecha', models.DateField(auto_now_add=True, null=True)),
                ('problemaLibro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.libros', verbose_name='Libro o Guia')),
                ('problemaSolucionadoPor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.solucionadores', verbose_name='Solucionado por')),
                ('problemaTema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.tematicas', verbose_name='Tema del problema')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemaPaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paqueteID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.paquetes')),
                ('problemaID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.soluciones')),
            ],
        ),
        migrations.AddField(
            model_name='paquetes',
            name='paquetePerfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.perfil', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='libros',
            name='perfilId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.perfil', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='concursos',
            name='Asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.perfil'),
        ),
        migrations.AddField(
            model_name='concursos',
            name='CreadoPor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concursos',
            name='Tema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.tematicas'),
        ),
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('respuesta', models.TextField(max_length=150, null=True)),
                ('responsable', models.IntegerField(null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
