# Generated by Django 3.0.6 on 2022-08-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='solucionesConcursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIni', models.DateField(blank=True, null=True)),
                ('problemaConcurso', models.FileField(null=True, upload_to='solucion', verbose_name='solucion')),
            ],
        ),
    ]
