# Generated by Django 3.0.6 on 2022-08-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0002_solucionesconcursos'),
    ]

    operations = [
        migrations.AddField(
            model_name='solucionesconcursos',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solucionesconcursos',
            name='usuario',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='solucionesconcursos',
            name='fechaIni',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
