# Generated by Django 3.2.15 on 2023-12-04 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0003_auto_20231204_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='temaLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.tematicas')),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Soluciones.libros')),
            ],
        ),
        migrations.DeleteModel(
            name='QRPago111',
        ),
    ]
