# Generated by Django 3.0.6 on 2022-09-14 21:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Soluciones', '0004_auto_20220911_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='salas',
            name='clave',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salas',
            name='dueño',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mensajes',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 14, 17, 0, 53, 778521)),
        ),
    ]
