# Generated by Django 3.2.15 on 2024-01-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Soluciones', '0004_auto_20231204_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='tematicas',
            name='resumenTema',
            field=models.FileField(null=True, upload_to='soluciones', verbose_name='Resumen de tema'),
        ),
    ]
